version: 1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm install 1.0.0-rc1-update1
before_build:
- cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
- cmd: dnu publish "src\AppVeyorSample" --out DeployPackage --configuration Release --runtime dnx-clr-win-x86.1.0.0-rc1-update1 --wwwroot-out "wwwroot" --quiet
build:
  verbosity: minimal
test_script:
- cmd: dnu restore test -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
- cmd: cd test\AppVeyorSample.Tests
- cmd: dnx test
artifacts:
- path: DeployPackage
  name: DeployPackage
deploy:
- provider: WebDeploy
  server: https://<site>.scm.azurewebsites.net:443/msdeploy.axd?site=<site>
  website: <site>
  username: $<site>
  password:
    secure: <password>
  aspnet_core: true
  remove_files: true
  app_offline: true
  aspnet_core_force_restart: true
